### ISSUE TITLE
有人知道为什么 ubuntu下运行只能接收消息，而不能回应消息？

### ISSUE THREAD

**Issue by HarukiMisora** [FloatTech/gocqzbp#16]
![image](https://user-images.githubusercontent.com/82428526/178953520-ad1e24ba-3554-42ef-8655-5d039836aa5e.png)

![image](https://user-images.githubusercontent.com/82428526/178953605-f48a6d02-594a-4c28-89f4-3ef2ffa25146.png)
跟这三个警告中的一个有关系吗？

**Comment by fumiama** [comment]
https://github.com/FloatTech/ZeroBot-Plugin/issues/311
