### ISSUE TITLE
通过代码写死的方式添加主人账号的问题

### ISSUE THREAD

**Issue by Potccv** [FloatTech/gocqzbp#17]
我在通过代码写死的方式添加主人账号这么改结果报错停了，请问要怎么更正？
![QQ图片20220717212356](https://user-images.githubusercontent.com/109468579/179400497-5976f456-ea04-44af-9ea7-afbd3601922d.png)
![QQ图片20220717212401](https://user-images.githubusercontent.com/109468579/179400501-101e6fbd-d533-4fdd-b320-276e75e54930.png)
![QQ图片20220717212405](https://user-images.githubusercontent.com/109468579/179400502-710e7774-4cac-4fde-99e3-f29f7cbf233d.png)

**Comment by Potccv** [comment]
此错误发生在自己手动生成docker镜像的过程中

**Comment by fumiama** [comment]
注释没改，现在是
```go
[]int64{12345678, 877654321}
```
另外，建议用命令行传入主人账号
