### ISSUE TITLE
1.5.0版本问题

### ISSUE THREAD

**Issue by Chinzicam** [FloatTech/gocqzbp#18]
1.5.0版本除去/服务详情，/启用xxx，/禁用xxx有回复，其余所有功能发指令都无反应
data里绝大部分功能对应的文件也没有自动下载

把之前安装过的1.4.1版本data文件全部复制过去功能也没用

**Comment by Chinzicam** [comment]
另外新版的**服务详情**图有点太大了
![image](https://user-images.githubusercontent.com/108013361/184873954-7db727a5-dee0-48cf-adcc-a14ea30f0007.png)
![image](https://user-images.githubusercontent.com/108013361/184873977-0a3489c5-bf2a-4b62-b0f0-f174014810f4.png)
体积翻几倍233333

**Comment by fumiama** [comment]
有人有相同情况吗？

**Comment by Chinzicam** [comment]
> 有人有相同情况吗？

今天才有的1.5.0正式版，周围暂时还没人更新......

**Comment by Sayafx** [comment]
> 1.5/取消服务详情，/启用xxx，/禁用回复，其他所有功能都可以发指令都无反应xxx有0个版本 自动下载的文件也没有
> 
> 把安装之前的1.4.1版本数据文件全部复制过去的功能不用

刚刚试着更新一下，确实原先自动下载的文件现在无法正常自动下载了
![image](https://user-images.githubusercontent.com/97787820/185307693-acfa10ce-60c3-4bf4-8adf-e2ec9633a78c.png)

**Comment by Chinzicam** [comment]
> 有人有相同情况吗？

没事了我的锅...........太久没更新zbp了，造成问题的原因是没有先**/响应**
