### ISSUE TITLE
配置密码后仍然需要扫码

### ISSUE THREAD

**Issue by ek1ng** [FloatTech/gocqzbp#5]
![image](https://user-images.githubusercontent.com/72065582/165052744-6bd5a037-97ca-4b08-9a33-81c01f3b9cc1.png)
而且扫码会显示登录异常，无法登录，尝试用miraiAndroid导出device.json更换仍然无效

**Comment by fumiama** [comment]
实在抱歉，请移步[go-cqhttp](https://github.com/Mrs4s/go-cqhttp)提问，这里不负责解决gocq相关问题，也没有能力解决。
